site_url: https://hugo-site-dup.pages.dev/
display_url: https://hugo-site-dup.pages.dev/
publish_mode: editorial_workflow

# Uncomment below to show preview links in the UI
# show_preview_links: true 

# Uncomment below to enable drafts https://www.decapcms.org/docs/add-to-your-site/#editorial-workflow
# publish_mode: editorial_workflow

# Uncomment below to enable a link to your published site in the header bar of Decap CMS
# site_url: https://hugo-site-dup.pages.dev/


backend:
  name: github
  repo: mugi2/hugo-site
  branch: main
  site_domain: https://hugo-site-dup.pages.dev/
  base_url: https://hugo-site-dup.pages.dev/
  auth_endpoint: /api/auth
  squash_merges: true
  preview_context: 'cloudflare preview deploy'
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  # Podcast episodes
  - name: "episodes" # Used in routes, e.g., /admin/collections/blog
    label: "Episodes" # Used in the UI
    folder: "content/episodes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Audio URL", name: "audio_url", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }